sudo: required
language: go
go: "1.10"
gobuild_args: -x -ldflags "-X main.VersionString v${TRAVIS_TAG:-0.0.0} -a -installsuffix cgo"

env: GOOS=linux GOARCH=amd64

services:
  - docker

before_script:
  - curl -s -L https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script: go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - dep ensure
  - rm -f env-aws-params
  - go build
  - zip env-aws-params_${TRAVIS_TAG}_linux_amd64.zip env-aws-params
  - rm -f env-aws-params
  - docker run --rm -t -e TRAVIS_TAG=${TRAVIS_TAG} -v `pwd`:/go/src/env-aws-params -w /go/src/env-aws-params gavinmroy/golang-build:1.10.1 make
  - zip env-aws-params_${TRAVIS_TAG}_alpine-linux_amd64.zip env-aws-params

deploy:
  provider: releases
  api_key:
    secure: OTrokvVlY1BE0o0qO+6EYcuBk5gY9jVg7zavN0+uYbeL6lztv8YPNOlevAltdiKW+37VzTvdXuY4B0ht6HkxttCaKXe6BDYoA117HpcSoqKqVHi7HvLgB7tEumQ1g2NulCd7tger04uskk3jcCns4wRsg8TYy/QhtiegIxjQz4tEmPMeIZclV3clJZB6EbDNXac3MWVQpZutNahUhGAb/YczKGJY/ElwBMhzzbE6Jbhultj/dr80VtAJNKFp/PTYCFovIfIlGDQTDHb2b7c9SpfDfOiLcW/97JwpwcAYVuyG3/YhozqaVrDvGDHtdTuDuSzbMe9aB0KruVEb7fwXSRnodaQzeFXUqLQ0RZqhY0SQ+h0FVs7YlTKiveM9B2ejoPL+Lb34XnaMcUfwHdB+bafqXYqYkbWGCv7GO2wvxVcsMapvL4b9LLLonoi7zJClBIHS0aDYeHmDIw4DnIJAOSvDgcDZgHgKyGaeGs4Y19sHZ/C6nTihWpkAeWMRrL05eYuBBNUvgufUPurEnLUpbcbCNK/xXknsIr1yDXYxy6znTY/Q4dN7rY39LRMth2GFiZuvSpKGHcTkZIwUG9XJj+Cifr8zp19HPCuWz5r3HsqSkA4Y0GaIhTQsow3DIJ+jZGdhjVnMQzFiYyV5ya98ea/84HzEt+Ovbe1O7TBbrnU=
  file:
    - "env-aws-params_${TRAVIS_TAG}_alpine-linux_amd64.zip"
    - "env-aws-params_${TRAVIS_TAG}_linux_amd64.zip"
  on:
    repo: notonthehighstreet/env-ssm
    tags: true
  skip_cleanup: true
